server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri /index.html;
    }

    location /api/auth-svc/ {
        proxy_pass http://auth-service:3005/;
    }

    location /api/tickets-svc/ {
        proxy_pass http://ticket-service:3001/;
    }

    location /api/support-svc/ {
        proxy_pass http://support-service:3002/;
    }

    location /api/notifications-svc/ {
        proxy_pass http://notification-service:3003/;
    }

    location /api/reports-svc/ {
        proxy_pass http://reporting-service:3004/;
    }
}