apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: supportdesk-prod
type: Opaque
stringData:
  tickets-uri: "mongodb+srv://amira:amira123@cluster0.avavr8w.mongodb.net/ticketsDB_prod?appName=Cluster0&retryWrites=true&w=majority"
  support-uri: "mongodb+srv://amira:amira123@cluster0.avavr8w.mongodb.net/supportDB_prod?appName=Cluster0&retryWrites=true&w=majority"
  notifications-uri: "mongodb+srv://amira:amira123@cluster0.avavr8w.mongodb.net/notificationsDB_prod?appName=Cluster0&retryWrites=true&w=majority"