apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: support-system
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://amira:amira123@cluster0.avavr8w.mongodb.net/authDB_prod?appName=Cluster0&retryWrites=true&w=majority"
---
apiVersion: v1
kind: Secret
metadata:
  name: ticket-secret
  namespace: support-system
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://amira:amira123@cluster0.avavr8w.mongodb.net/ticketsDB_prod?appName=Cluster0&retryWrites=true&w=majority"
---
apiVersion: v1
kind: Secret
metadata:
  name: support-secret
  namespace: support-system
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://amira:amira123@cluster0.avavr8w.mongodb.net/supportDB_prod?appName=Cluster0&retryWrites=true&w=majority"
---
apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
  namespace: support-system
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://amira:amira123@cluster0.avavr8w.mongodb.net/notificationsDB_prod?appName=Cluster0&retryWrites=true&w=majority"
